config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'

  root 'store#index'

  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    put 'remove/:product_id', to: 'carts#remove', as: :remove_from
  end

  resource :session, :only => [:new, :create, :destroy]

  resources :store
  resources :products
  resources :categories
  namespace :admin do
    resources :dashboard, only: :index
    resources :users do
      resources :credit_cards
    end
    resources :categories
    resources :products
    resources :addresses
    resources :orders do
      resources :order_contents
    end
  end

end

app/controllers/admin/addresses_controller.rb
class Admin::AddressesController < AdminController

def new
  @address = Address.new( :user_id => params[:user_id])
  @states = State.all
end

def create
  @address = Address.new(whitelist_params)
  # @user_id = params[:address][:user_id]
  @states = State.all
  if @address.save
    flash[:success] = "New address created"
    redirect_to [:admin, user_path(@address.user_id)]
  else
    flash.now[:error] = "Address failed to save"
    render :new
  end
end

def index
  if User.exists?(params[:user_id])
    @addresses = Address.where( :user_id => params[:user_id])
    @user = User.find(params[:user_id])
  else
    @addresses = Address.all
  end
end

def show
	@address = Address.find(params[:id])
end

def edit
  @address = Address.find(params[:id])
  @states = State.all
end

def update
  @address = Address.find(params[:id])
  @states = State.all
  if @address.update(whitelist_params)
    flash[:success] = "Address updated"
    redirect_to [:admin, user_path(@address.user_id)]
  else
    flash.now[:error] = "Address failed to save"
    render :edit
  end
end

def destroy
  @address = Address.find(params[:id])
  if @address.destroy
    flash[:success] = "Address destroyed"
    redirect_to [:admin, addresses_path]
  else
    flash[:error] = "Address not destroyed"
    render :edit
  end
end

private

def whitelist_params
  params[:address][:city_id] = find_or_create_city
  params.require(:address).permit(:street_address, :secondary_address, :city_id, :state_id, :zip_code, :user_id)
end

def find_or_create_city
  result = City.select(:id).where("name = ?", params[:address][:city])
  if result.first
    result = result.first.id
  else
    c = City.new(name: params[:address][:city])
    c.save
    result = c.id
  end
  result
end


end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/admin/addresses/_address_form.html.erb
<%= form_for [:admin, @address] do |f| %>

 	<% @address.errors.full_messages.each do |e| %>
 	<%= e %> <br>
 	<% end %>

	<p>Owner ID: <%= @address.user.id %> </p>
	<p>Owner name: <%= link_to "#{@address.user.full_name} (click to view user)", admin_user_path(@address.user.id) %></p>
	<p>
	 	<%= f.label :street_address %>
	 	<%= f.text_field :street_address %>
	</p>
	<p>
	 	<%= f.label :secondary_address %>
	 	<%= f.text_field :secondary_address %>
	</p>
	<p>
	 	<%= f.label :city %>
	  	<% if @address.persisted? %>
	  		<%= f.text_field :city, value: @address.city.name %>
  		<% else %>
				<%= f.text_field :city %>
			<%end%>
	</p>
	<p>
	 	<%= f.label :state_id %>
		<%= f.collection_select :state_id,
	                          @states,
	                          :id,
	                          :name %>
	</p>
	<p>
	  <%= f.label :zip_code %>
	 	<%= f.text_field :zip_code %>
	</p>
	 	<%= f.hidden_field :user_id, value: "#{@address.user.id}" %>

  <% if @address.persisted? %>
  <p>
	 	<%= f.submit "Update Address"%>
	</p>
  <% else %>
  <p>
	 	<%= f.submit "Create New Address"%>
	</p>
	<% end %>
<% end %>

app/views/admin/addresses/edit.html.erb
<h2> Edit <%= @address.user.full_name %>'s Address </h2>

<%= render :partial => 'address_form' %>

<%= link_to "Delete Address", admin_address_path(@address.id), method: :delete, data: { confirm: "Are you sure?" } %>

app/views/admin/addresses/index.html.erb
<%= render partial: 'shared/admin_nav' %>

<div class = "col-sm-9 text-center">

  <% if @user %>
    <h2><%= @user.full_name%>'s Addresses</h2>

    <div class = "row">
      <div class = "col-sm-12">
        <%= link_to "Create a #{@user.full_name} Address", new_admin_address_path(:user_id => @user.id), type: 'button', class: 'btn btn-lg btn-primary'%>
      </div>
    </div>

  <% else %>

    <h2>Addresses</h2>
    <h5> Create new addresses from within
      <%= link_to "User", admin_users_path %>
      profiles
    </h5>

  <% end %>

  <div class = "row">
    <div class = "col-sm-12">
      <table class="table table-hover table-striped">
          <tr>
            <th>ID</th>
            <th>User</th>
            <th>Street Address</th>
            <th>City</th>
            <th>State</th>
            <th>Orders</th>
            <th>Created at</th>
            <th>Show</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
          <% @addresses.each do |add| %>
            <tr>
              <td> <%= add.id %> </td>
              <td> <%= link_to add.user.full_name, admin_user_path(add.user.id) %> </td>
              <td> <%= add.street_address %> </td>
              <td> <%= add.city.name %> </td>
              <td> <%= add.state.name %> </td>
              <td> <%= add.user.orders.count %> </td>
              <td> <%= add.created_at %> </td>
              <td> <%= link_to 'Show', admin_address_path(add.id) %> </td>
              <td> <%= link_to 'Edit', edit_admin_address_path(add.id) %> </td>
              <td> <%= link_to 'Delete', admin_address_path(add.id),
                        method: :delete,
                        class: "alert-danger",
                        data: { confirm: "Are you sure?" } %> </td>
            </tr>
          <% end %>

      </table>
    </div>
  </div>
</div>

app/views/admin/addresses/new.html.erb
<h2> <%= @address.user.full_name %>'s Address </h2>

<%= render :partial => 'address_form' %>

app/views/admin/addresses/show.html.erb
<h2> <%= @address.user.full_name %>'s Address </h2>

<p>Owner ID: <%= @address.user.id %> </p>
<p>Owner name: <%= link_to "#{@address.user.full_name} (click to view user)", admin_user_path(@address.user.id) %></p>
<p>Street <%= @address.street_address %> </p>
<p>City <%= @address.city.name %> </p>
<p>State <%= @address.state.name %> </p>
<p>Zipcode <%= @address.zip_code %> </p>

<p><%= link_to "Edit Address", edit_admin_address_path(@address.id) %> </p>
<p><%= link_to "Delete Address", admin_address_path(@address.id), :method => :delete, data: { confirm: "Are you sure?" } %> </p>