config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'

  root 'store#index'

  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    put 'remove/:product_id', to: 'carts#remove', as: :remove_from
  end

  resource :session, :only => [:new, :create, :destroy]

  resources :store
  resources :products
  resources :categories
  namespace :admin do
    resources :dashboard, only: :index
    resources :users do
      resources :credit_cards
    end
    resources :categories
    resources :products
    resources :addresses
    resources :orders do
      resources :order_contents
    end
  end

end

app/models/order.rb
class Order < ActiveRecord::Base

  belongs_to :user
  has_many :order_contents, dependent: :destroy
  has_many :products, through: :order_contents
  has_many :categories, through: :products
  belongs_to :shipping_address, class_name: "Address", foreign_key: :shipping_id
  belongs_to :billing_address, class_name: "Address", foreign_key: :billing_id

  accepts_nested_attributes_for :order_contents,
                                :reject_if => :all_blank,
                                :allow_destroy => :true

  def value
    products.sum("quantity * price")
  end

  def status
    checkout_date ? "PLACED" : "UNPLACED"
  end

  def self.time_series_day(days=7)

    self.select("date_trunc('day', orders.checkout_date) AS day, count(DISTINCT orders.id), SUM(order_contents.quantity * products.price)").
    join_to_products.
    where('orders.checkout_date >= ? AND orders.checkout_date < ?',
      DateTime.now - 7,DateTime.now).
    group('day').
    order('day DESC')
  end

  def self.time_series_week(weeks=7)

    self.select("date_trunc('week', orders.checkout_date) AS week, count(DISTINCT orders.id), SUM(order_contents.quantity * products.price)").
    join_to_products.
    where('orders.checkout_date >= ? AND orders.checkout_date < ?',
      DateTime.now - (7 * weeks), DateTime.now).
    group('week').
    order('week DESC')
  end

  def self.get_statistics
    overall = {'Last 7 Days' => 7, 'Last 30 Days' => 30, 'Total' => nil}
    overall.each do |key, limit|
      result = []
      result << ["Number of Orders", self.in_last(limit)]
      result << ["Total Revenue", self.revenue_in_last(limit)]
      result << ["Average Order Value", self.average_in_last(limit)]
      result << ["Largest Order Value", self.largest_in_last(limit)]
      overall[key] = result
    end
    overall
  end

  def self.in_last(days=nil)
    if days.nil?
      self.count
    else
      self.where('checkout_date > ?', DateTime.now - days).count
    end
  end

  def self.revenue_in_last(days=nil)
    if days
      revenue.where('orders.checkout_date IS NOT NULL').first.cost
    else
      revenue.where('orders.checkout_date > ?', DateTime.now - days).first.cost
    end
  end

  def self.avg_in_last_helper
    self.select('(SUM(products.price * order_contents.quantity)/COUNT(DISTINCT orders.id)) as average_order').
      join_to_products
  end

  def self.average_in_last(days = nil)
    if days
      self.avg_in_last_helper.
      where('orders.checkout_date > ?', DateTime.now - days).order('1').first.average_order
    else
      self.avg_in_last_helper.
      where('orders.checkout_date IS NOT NULL').order('1').first.average_order
    end
  end


  def self.largest_in_last(days = nil)
    if days
      self.get_largest_overall.
      where('orders.checkout_date > ?', DateTime.now - days).
      group('orders.id').order('max_order DESC').first.max_order
    else
      self.get_largest_overall.
      where('orders.checkout_date IS NOT NULL').
      group('orders.id').order('max_order DESC').first.max_order
    end
  end

  def self.revenue_in_last(days)
    self.revenue(days).first.cost
  end

  private

  def self.get_largest_overall
    self.select('SUM(products.price * order_contents.quantity) as max_order').
    join_to_products
  end

  def self.revenue(days = nil)
    if days
      self.select('SUM(products.price * order_contents.quantity) as cost').
      join_to_products.
      where('orders.checkout_date > ?', DateTime.now - days).order('cost')
    else
      self.select('SUM(products.price * order_contents.quantity) as cost').
      join_to_products.
      order('cost')
    end
  end

  def self.join_to_order_contents
    self.joins('JOIN order_contents ON orders.id = order_contents.order_id')
  end

  def self.join_to_products
    self.join_to_order_contents.joins('JOIN products ON products.id = order_contents.product_id')
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController

  def index
    if User.exists?(params[:user_id])
      @orders = Order.where(:user_id => params[:user_id])
      @user = User.find(params[:user_id])
      @title = "Viking Store Orders for #{@user.full_name}"
      @show_all = false
    else
      @orders = Order.all
      @title = "Viking Store All Orders"
      @show_all = true
    end
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @user = User.find(params[:user_id])
    @order = @user.orders.new
  end

  def create
    @order = Order.new(whitelisted_params)
    @order.user_id = params[:order][:user_id]
    if @order.save
      flash[:success] = "Order Created!"
      redirect_to [:admin, edit_order_path(@order)]
    else
      flash[:error] = "Failed to Create Order"
      render :new
    end
  end

  def edit
    @order = Order.find(params[:id])
    @order_contents = OrderContent.where(:order_id => @order.id)
    @order.order_contents.build(:quantity => nil)
    @order.order_contents.build(:quantity => nil)
    @order.order_contents.build(:quantity => nil)
    @order.order_contents.build(:quantity => nil)
    @order.order_contents.build(:quantity => nil)
  end

  def update
    product_id_arr = []
    @order = Order.find(params[:id])
    array_order_contents = params[:order][:order_contents_attributes]
    array_order_contents.length.times do |i|
      unless array_order_contents[i.to_s]["id"].to_i ==0
        @order_content = OrderContent.find((array_order_contents[i.to_s]["id"].to_i).to_i)
        @order_content.quantity = array_order_contents[i.to_s]["quantity"].to_i
        product_id_arr << array_order_contents[i.to_s]["product_id"].to_i
      end
    end
    # @order.product_ids = product_id_arr
    @order.order_contents.product
    if @order.update(whitelisted_params)
      flash[:success] = "Order Updated!"
      redirect_to [:admin, order_path(@order)]
    else
      flash[:error] = "Order Failed to Update!"
      render :edit
    end

  end

  def destroy
    @order = Order.find(params[:id])
    if @order.destroy
      flash[:success] = "Order Deleted!"
      redirect_to [:admin, orders_path]
    else
      flash[:error] = "Order Failed to Delete!"
      redirect_to [:admin, orders_path]
    end
  end

  private

  def whitelisted_params
    params.require(:order).permit(:checkout_date, :user_id,
      :shipping_id, :billing_id, :order_contents_attributes =>[
      :order_id, :product_id, :quantity, :id])
  end


end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/_order_form.html.erb
<div class="col-sm-12 panel panel-default">
  <div class="panel-body">
    <h2 class='text-center'>
      Logistical Information
    </h2>
    <h3>
    Basic Information
    </h3>
    <table class="table">
      <tr>
        <td>Customer ID:</td>
        <td><%= @user.id %></td>
      </tr>
      <tr>
        <td>Customer</td>
        <td><%= link_to @user.full_name, admin_user_path(@user) %></td>
      </tr>
      <tr>
        <td>E-mail</td>
        <td><%= @user.email %></td>
      </tr>
      <tr>
        <td>Date Placed</td>
        <td>N/A</td>
      </tr>
    </table>
    <%= link_to "Edit Customer Profile", edit_admin_user_path(@user) %>
    <%= form_for [:admin, @order] do |f| %>
      <h3>
        Shipping Address
      </h3>
      <%= f.collection_select :shipping_id, @user.addresses, :id, :street_address, :html => {class: 'form-control'}%>
      <h3>
        Billing Address
      </h3>
      <%= f.collection_select :billing_id, @user.addresses, :id, :street_address, :html => {class: 'form-control'}%>
      <h3>
        Billing Card
      </h3>
      <select name="empty" id="cards">
        <%= @user.credit_cards.each do |card| %>
          <option>
            <%= card.card_number %>
          </option>
        <% end %>
      </select>
      <br>
      <br>
      <%= f.hidden_field :user_id %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/admin/orders/edit.html.erb
<div class="col-sm-12 panel panel-default">
  <div class="panel-body">
    <h2 class='text-center'>
      Logistical Information
    </h2>
    <h3>
    Basic Information
    </h3>
    <table class="table">
      <tr>
        <td>Customer ID:</td>
        <td><%= @order.user_id %></td>
      </tr>
      <tr>
        <td>Customer</td>
        <td><%= link_to @order.user.full_name, admin_user_path(@order.user) %></td>
      </tr>
      <tr>
        <td>E-mail</td>
        <td><%= @order.user.email %></td>
      </tr>
      <tr>
        <td>Date Placed</td>
        <td>N/A</td>
      </tr>
    </table>
    <%= link_to "Edit Customer Profile", edit_admin_user_path(@order.user) %>
    <%= form_for @order do |f| %>

      <h3>
        Order Status
      </h3>
      <p>PLACED</p>
      <%= f.radio_button :checkout_date, Date.today %>
      <p>UNPLACED</p>
      <%= f.radio_button :checkout_date, nil %>
      <h3>
        Shipping Address
      </h3>
      <%= f.collection_select :shipping_id, @order.user.addresses, :id, :street_address, :html => {class: 'form-control'}%>
      <h3>
        Billing Address
      </h3>
      <%= f.collection_select :billing_id, @order.user.addresses, :id, :street_address, :html => {class: 'form-control'}%>
      <h3>
        Billing Card
      </h3>
      <select name="empty" id="cards">
        <%= @order.user.credit_cards.each do |card| %>
          <option>
            <%= card.card_number %>
          </option>
        <% end %>
      </select>
      <br>
      <br>
      <%= f.hidden_field :user_id %>
      <%= f.submit %>
    <% end %>
  </div>
</div>
<div class="col-sm-12 panel panel-default" data-no-turbolink >
  <div class="panel-body">
    <h2>
      Order Contents
    </h2>
    <table class="table table-striped">
      <tr>
        <th>ID</th>
        <th>Product</th>
        <th>Quantity</th>
        <th>Price</th>
        <th>Total Price</th>
        <th>REMOVE</th>
      </tr>

      <%= form_for [:admin, @order] do |f| %>
      <% count = 1 %>
        <%= f.fields_for :order_contents do |order_fields| %>
          <% if order_fields.object.persisted? %>
            <tr>
              <td><%= count %></td>
              <% count += 1 %>
              <% order_fields.object.id %>
              <td><%= order_fields.object.product.name %></td>
              <td><%= order_fields.text_field :quantity %></td>
              <td><%= order_fields.object.product.price %></td>
              <td><%= order_fields.object.product.price * order_fields.object.quantity %></td>
              <!-- <input type = "hidden" name="order[order_contents_attributes][#i" value="" -->
              <%= order_fields.hidden_field :product_id %>
              <td><%= link_to "Remove", admin_order_order_content_path(@order.id, order_fields.object), method: :delete %>
            </tr>
          <% end %>

        <% end  %>
        <tr>
        <td><%= f.submit %></td>
        </tr>
      <% end %>

    </table>
    <%= link_to "Edit Order", edit_admin_order_path(@order) %>
    <br>
    <%= link_to "Delete Order", admin_order_path(@order), method: :delete %>
  </div>
</div>
<div class="col-sm-12 panel panel-default" data-no-turbolink >
  <div class="panel-body">
    <h2>
      Add Products to Order
    </h2>
    <table class="table table-striped">
      <tr>
        <th>ProductID</th>
        <th>Quantity</th>
      </tr>

      <%= form_for [:admin, @order] do |f| %>
        <%= f.fields_for :order_contents do |order_fields| %>
          <% unless order_fields.object.persisted? %>
            <tr>
              <td><%= order_fields.text_field :product_id %></td>
              <td><%= order_fields.text_field :quantity %></td>
            </tr>
          <% end %>

        <% end  %>
         <%= f.submit %>
      <% end %>
    </table>
  </div>
</div>

app/views/admin/orders/index.html.erb
<%= render partial: 'shared/admin_nav' %>

<div class = "col-sm-9 text-center">

  <h2><%= @title %></h2>

  <div class = "row">
    <div class = "col-sm-12 text-center">
      <% if @show_all %>
        <h4><em>Create new orders from within <%= link_to "User", admin_users_path %> profiles.</em></h4>
      <% else %>
        <%= link_to admin_new_order_path(:user_id => @user.id) do %>
          <%= button_tag(type: 'button', class: 'btn btn-lg btn-primary') do
                content_tag(:strong, 'Create New Order!') end %>
        <% end %>
      <% end %>
    </div>
  </div>

  <hr>

  <div class = "row">
    <div class = "col-sm-12">
      <table class="table table-hover table-striped">
          <tr>
            <th>ID</th>
            <th>UserID</th>
            <th>Address</th>
            <th>City</th>
            <th>State</th>
            <th>Total Value</th>
            <th>Status</th>
            <th>Date Placed</th>
            <th>Show</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
          <% @orders.each do |order| %>
            <tr>
              <td> <%= order.id %> </td>
              <td> <%= link_to order.user.id, admin_user_path(order.user.id) %> </td>
              <td> <%= order.user.default_shipping_address.street_address unless order.user.default_shipping_address.nil? %> </td>
              <td> <%= order.user.default_shipping_address.city.name unless order.user.default_shipping_address.nil? %> </td>
              <td> <%= order.user.default_shipping_address.state.name unless order.user.default_shipping_address.nil? %> </td>
              <td> <%= order.value %> </td>
              <td> <%= order.status %> </td>
              <td> <%= order.checkout_date.strftime("%Y-%m-%d") unless order.checkout_date.nil? %> </td>
              <td> <%= link_to 'Show', [:admin, order] %> </td>
              <td> <%= link_to 'Edit', edit_admin_order_path(order) %> </td>
              <td> <%= link_to 'Delete', admin_order_path(order),
                        method: :delete,
                        class: "alert-danger",
                        data: { confirm: "Are you sure?" } %> </td>
            </tr>
          <% end %>

      </table>
    </div>
  </div>
</div>

app/views/admin/orders/new.html.erb
<%= render :partial => 'order_form' %>

app/views/admin/orders/show.html.erb
<div class="col-sm-12 text-center">
  <h1>Order <%= @order.id %></h1>
</div>
<div class="col-sm-12 panel panel-default">
  <div class="panel-body">
    <h2 class='text-center'>
      Logistical Information
    </h2>
    <h3>
    Basic Information
    </h3>
    <table class="table">
      <tr>
        <td>Customer ID:</td>
        <td><%= @order.user_id %></td>
      </tr>
      <tr>
        <td>Customer</td>
        <td><%= link_to @order.user.full_name, admin_user_path(@order.user) %></td>
      </tr>
      <tr>
        <td>E-mail</td>
        <td><%= @order.user.email %></td>
      </tr>
      <tr>
        <td>Date Placed</td>
        <td><%= @order.checkout_date.strftime("%m/%d/%Y") if @order.checkout_date %></td>
      </tr>
      <tr>
        <td>Products</td>
        <td><%= @order.products.count %></td>
      </tr>
      <tr>
        <td>Order Value</td>
        <td>$<%= @order.value %></td>
      </tr>
    </table>
    <%= link_to "Edit Customer Profile", edit_admin_user_path(@order.user) %>
    <h3>
      Order Status
    </h3>
    <h2>
      <%= @order.status.html_safe%>
    </h2>
    <h3>
      Shipping Address
    </h3>
    <table class="table">
      <tr>
        <td>Street</td>
        <td><%= @order.shipping_address.street_address %></td>
      </tr>
      <tr>
        <td>City</td>
        <td><%= @order.shipping_address.city.name %></td>
      </tr>
      <tr>
        <td>State</td>
        <td><%= @order.shipping_address.state.name %></td>
      </tr>
    </table>
    <h3>
      Billing Address
    </h3>
    <table class="table">
      <tr>
        <td>Street</td>
        <td><%= @order.billing_address.street_address %></td>
      </tr>
      <tr>
        <td>City</td>
        <td><%= @order.billing_address.city.name %></td>
      </tr>
      <tr>
        <td>State</td>
        <td><%= @order.billing_address.state.name %></td>
      </tr>
    </table>
    <h3>
      Billing Card
    </h3>
    <table class="table">
      <tr>
        <td>Last Four Digits</td>
        <td><%= @order.user.credit_cards.first.card_number %></td>
      </tr>
    </table>
    <%= link_to "Edit Order", edit_admin_order_path(@order) %>
    <br>
    <%= link_to "Delete Order", admin_order_path(@order), method: :delete %>
  </div>
</div>

<div class="col-sm-12 panel panel-default">
  <div class="panel-body">
    <h2>
      Order Contents
    </h2>
    <table class="table">
      <tr>
        <th>ProductID</th>
        <th>Product</th>
        <th>Quantity</th>
        <th>Price</th>
        <th>Total Price</th>
      </tr>
      <% OrderContent.where(:order_id => @order.id).each do |o| %>
        <tr>
          <td><%= o.product_id %></td>
          <td><%= o.product.name %></td>
          <td><%= o.quantity %></td>
          <td>$<%= o.product.price %></td>
          <td>$<%= o.quantity * o.product.price %></td>
        </tr></tr>
      <% end %>
    </table>
    <%= link_to "Edit Order", edit_admin_order_path(@order) %>
    <br>
    <%= link_to "Delete Order", admin_order_path(@order), method: :delete %>
  </div>
</div>