config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'

  root 'store#index'

  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    put 'remove/:product_id', to: 'carts#remove', as: :remove_from
  end

  resource :session, :only => [:new, :create, :destroy]

  resources :store
  resources :products
  resources :categories
  namespace :admin do
    resources :dashboard, only: :index
    resources :users do
      resources :credit_cards
    end
    resources :categories
    resources :products
    resources :addresses
    resources :orders do
      resources :order_contents
    end
  end

end

app/views/shared/_admin_nav.html.erb
<div class = "row">
  <div class = "col-sm-12 text-center">
    <h1>Viking Store Admin Portal</h1>
  </div>
</div>
<hr>

<div class = "row">
  <div class = "col-sm-3">

    <h4 class = "text-center">Navigation Options</h4>

    <div class = "row">
      <div class = "col-sm-12">
        <%= link_to 'Users', admin_users_path %>
      </div>
    </div>

    <div class = "row">
      <div class = "col-sm-12">
       <%= link_to 'Addresses', admin_addresses_path %>
      </div>
    </div>

    <div class = "row">
      <div class = "col-sm-12">
        <%= link_to 'Orders', admin_orders_path %>
      </div>
    </div>

    <div class = "row">
      <div class = "col-sm-12">
        <%= link_to 'Products', admin_products_path %>
      </div>
    </div>

    <div class = "row">
      <div class = "col-sm-12">
        <%= link_to 'Categories', admin_categories_path %>
      </div>
    </div>

    <hr>

    <div class = "row">
      <div class = "col-sm-12 text-center">
        <%= link_to 'Analytics Dashboard', admin_dashboard_index_path %>
      </div>
    </div>

  </div>

app/views/shared/_navbar.html.erb
<!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "Viking Store", root_path, class: "navbar-brand" %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <%= link_to "View Cart #{@cart_count}", root_path %>
                    </li>
                    <li>
                        <%= link_to "Sign In", root_path %>
                    </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

app/views/shared/_user_order_history.html.erb
<div class = "row">
    <div class = "col-sm-12">
      <h4>Order History</h4>
        <div class = "row">
    <div class = "col-sm-12">
      <table class="table table-hover table-striped">
          <tr>
            <th>ID</th>
            <th>Order Date</th>
            <th>Order Value</th>
            <th>Status</th>
            <th>Show</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
          <% user.orders.each do |order| %>
            <tr>
              <td> <%= order.id %> </td>
              <td> <%= order.updated_at %> </td>
              <td> <%= order.value %> </td>
              <td> <span class="order-status"><%= order.status %> </span></td>
              <td> <%= link_to 'Show', 'order' %> </td>
              <td> <%= link_to 'Edit', 'edit_order_path(order)' %> </td>
              <td> <%= link_to 'Delete', 'order_path(order)',
                        method: :delete,
                        class: "alert-danger",
                        data: { confirm: "Are you sure?" } %> </td>
            </tr>
          <% end %>
      </table>
    </div>
  </div>