config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'

  root 'store#index'

  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    put 'remove/:product_id', to: 'carts#remove', as: :remove_from
  end

  resource :session, :only => [:new, :create, :destroy]

  resources :store
  resources :products
  resources :categories
  namespace :admin do
    resources :dashboard, only: :index
    resources :users do
      resources :credit_cards
    end
    resources :categories
    resources :products
    resources :addresses
    resources :orders do
      resources :order_contents
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :addresses, dependent: :destroy
  belongs_to :default_billing_address, class_name: "Address", foreign_key: :billing_id
  belongs_to :default_shipping_address, class_name: "Address", foreign_key: :shipping_id

  has_many :orders
  has_many :credit_cards, dependent: :destroy
  has_many :order_contents, :through => :orders
  has_many :products, through: :order_contents

  validates :first_name, :last_name, :email, :length => {:in => 1..64}  #, :message => "length must be between 1 and 64 characters"
  validates :email, :format => {:with => /@/}  # :message => "must be valid"

  before_destroy :empty_cart

  # after_destroy :destroy_unused_addresses

  # def destroy_unused_addresses
  #   self.addresses.each do |add|
  #     add.destroy if self.add.check_order_affliation
  #   end
  # end

  # Admin Portal methods
  def empty_cart
    orders.where("checkout_date IS NULL").each do |cart|
      cart.destroy
    end
  end

  def last_order_date
    query = User.select("orders.checkout_date AS checkout")
                .join_to_orders
                .where("orders.checkout_date IS NOT NULL AND users.id = ?", id)
                .order("orders.checkout_date DESC")
                .first
    if query
      query.checkout.to_date
    else
      "No Orders"
    end
  end

  def total_orders
    User.select("orders.id")
         .join_to_orders
         .where("orders.checkout_date IS NOT NULL AND users.id = ?", id)
         .count
  end

  def full_name
    self.first_name + " " + self.last_name
  end

  def find_state_name
    User.select("states.name AS state_name")
    .join_to_states
    .where("users.id = ?", id)
    .first.state_name
  end

  def find_city_name
    User.select("cities.name AS city_name")
        .join_to_cities
        .where("users.id = ?", id)
        .first.city_name
  end

  # Dashboard methods

  def self.in_last(days = nil)
    if days.nil?
      self.count
    else
      self.where('created_at > ?', DateTime.now - days).count
    end
  end

  def self.get_overall
    overall = {'Last 7 Days' => 7, 'Last 30 Days' => 30, 'Total' => nil}
    overall.each do |key, limit|
      result = []
      result << ["New Users", self.in_last(limit)]
      result << ["Orders", Order.in_last(limit)]
      result << ["New Products", Product.in_last(limit)]
      result << ["Revenue", Order.revenue_in_last(limit)]
      overall[key] = result
    end
    overall
  end

  def self.get_demographics
    demographics = {'Top 3 states' => [], 'Top 3 cities' => [] }
    self.top_states.each do |state|
      demographics['Top 3 states'] << [state.name, state.total]
    end

    self.top_cities.each do |state|
      demographics['Top 3 cities'] << [state.name, state.total]
    end
    demographics
  end

  def self.get_superlatives
    superlatives = {}
    highest_s = User.high_single_order_value.first
    superlatives['Highest Single Order Value'] = [highest_s.full_name,
                                                   highest_s.cost]
    highest_l = User.high_lifetime_value.first
    superlatives['Highest Lifetime Value'] = [highest_l.full_name,
                                               highest_l.cost]
    highest_a = User.high_average_value.first
    superlatives['Highest Average Order Value'] = [highest_a.full_name,
                                                    highest_a.average_value]
    m_orders = User.most_orders.first
    superlatives['Most Orders Placed'] = [m_orders.full_name,
                                           m_orders.number_of_orders]
    return superlatives
  end

  private

    def self.top_states(limit = 3)
      self.select('states.name, COUNT(addresses.state_id) AS total').
      join_to_states.
      group('states.name').
      order('COUNT(addresses.state_id) DESC').
      limit(limit)
    end

    def self.top_cities(limit = 3)
      self.select('cities.name, COUNT(addresses.city_id) AS total').
      join_to_cities.
      group('cities.name').
      order('COUNT(addresses.city_id) DESC').
      limit(limit)
    end

    def self.high_single_order_value
      self.select('users.first_name || users.last_name AS full_name, SUM(products.price * order_contents.quantity) as cost').
      join_to_products.
      where("orders.checkout_date IS NOT NULL").
      group('orders.id, full_name').order('cost DESC').limit(1)
    end

    # def self.high_single_order_value
    # self.select("users.id, SUM(products.price * order_contents.quantity) as cost")
    #     .join_to_products
    #     .where("orders.checkout_date IS NOT NULL")
    #     .group('orders.id, users.id').order('cost DESC').limit(1)
    # end

    def self.high_lifetime_value
      self.select('users.first_name AS fname, users.last_name AS , SUM(products.price * order_contents.quantity) as cost').
      join_to_products.
      where("orders.checkout_date IS NOT NULL").
      group('users.id, full_name').order('cost DESC').limit(1)
    end

    def self.high_average_value
      self.select('users.first_name || users.last_name AS full_name, SUM(products.price * order_contents.quantity)/(COUNT(DISTINCT orders.id)) as average_value').
      join_to_products.
      where("orders.checkout_date IS NOT NULL").
      group('users.id, full_name').order('average_value DESC').limit(1)
    end

    def self.most_orders
      self.select('users.first_name || users.last_name AS full_name, COUNT(orders.id) as number_of_orders').
      join_to_orders.
      where("orders.checkout_date IS NOT NULL").
      group('users.id, full_name').order('number_of_orders DESC').limit(1)
    end

    def self.join_to_orders
      self.joins('JOIN orders ON users.id = orders.user_id')
    end

    def self.join_to_order_contents
      self.join_to_orders.joins('JOIN order_contents ON order_contents.order_id = orders.id')
    end

    def self.join_to_products
      self.join_to_order_contents.joins('JOIN products ON order_contents.product_id = products.id')
    end

    def self.join_to_addresses
      self.joins('JOIN addresses ON users.billing_id = addresses.id')
    end

    def self.join_to_states
      self.join_to_addresses.joins('JOIN states ON states.id = addresses.state_id')
    end

    def self.join_to_cities
      self.join_to_addresses.joins('JOIN cities ON cities.id = addresses.city_id')
    end


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(whitelisted_params)
    if @user.save
      flash[:success] = "New User Created"
      redirect_to [:admin, @user]
    else
      flash[:error] = "Failed to Create New User"
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(whitelisted_params)
      flash[:success] = "User Updated"
      redirect_to [:admin, @user]
    else
      flash[:error] = "Failed to Update User"
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:success] = "User Deleted"
      redirect_to [:admin, users_path]
    else
      flash[:error] = "Failed to Delete User"
      render :edit
    end
  end

  private

  def whitelisted_params
    params.require(:user).permit(:first_name, :last_name, :email, :billing_id, :shipping_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def display_address(type, user)
    if user.default_billing_address && type == "billing"
      user.default_billing_address.full_address
    elsif user.default_shipping_address && type == "shipping"
      user.default_shipping_address.full_address
    else
      "No default #{type} address on file."
    end
  end
end

app/views/admin/users/_user_form.html.erb
<%= form_for [:admin, @user] do |f| %>
 	<% @user.errors.full_messages.each do |e| %>
 	<%= e %> <br>
 	<% end %>

 	<h2> Demographic Infomration </h2>

 	<%= f.label :first_name %>
 	<%= f.text_field :first_name %>

 	<%= f.label :last_name %>
 	<%= f.text_field :last_name%>

 	<%= f.label :email %>
 	<%= f.text_field :email %>

 	<% if @user.persisted? %>

	 	<%= f.label :default_billing_address %>
	 	<%= f.collection_select :billing_id,
                          @user.addresses,
                          :id,
                          :full_address %>

	 	<%= f.label :default_shipping_address %>
	 	<%= f.collection_select :shipping_id,
                          @user.addresses,
                          :id,
                          :full_address %>

	 	<%= link_to "View Saved Addresses", "#" %>

	 	<%= f.submit "Update #{@user.full_name}"%>

 	<% else %>
 			<%= f.submit "Create New User"%>
 	<% end %>

<% end %>

app/views/admin/users/edit.html.erb
  <%= render :partial => 'user_form' %>


 	<%= link_to "Delete", admin_user_path(@user.id), method: :delete %>

app/views/admin/users/index.html.erb
<%= render partial: 'shared/admin_nav' %>

<div class = "col-sm-9 text-center">

  <h2>Viking Store Users</h2>

  <div class = "row">
    <div class = "col-sm-12">
      <%= link_to new_admin_user_path do %>
        <%= button_tag(type: 'button', class: 'btn btn-lg btn-primary') do
              content_tag(:strong, 'Create New User!')
        end %>
      <% end %>
    </div>
  </div>

  <hr>

  <div class = "row">
    <div class = "col-sm-12">
      <table class="table table-hover table-striped">
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Join Date</th>
            <th>City</th>
            <th>State</th>
            <th>Orders</th>
            <th>Last order date</th>
            <th>Show</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
          <% @users.each do |user| %>
            <tr>
              <td> <%= user.id %> </td>
              <td> <%= user.full_name %> </td>
              <td> <%= user.created_at %> </td>
              <% if user.default_billing_address %>
                <td> <%= user.default_billing_address.city.name %> </td>
                <td> <%= user.default_billing_address.state.name %> </td>
              <% else %>
                <td> blank </td>
                <td> blank </td>
              <% end %>
              <td> <%= link_to user.total_orders, admin_orders_path(:user_id => user.id) %> </td>    <!-- ADD LINK -->
              <td> <%= user.last_order_date %> </td>
              <td> <%= link_to 'Show', [:admin, user] %> </td>
              <td> <%= link_to 'Edit', edit_admin_user_path(user) %> </td>
              <td> <%= link_to 'Delete', admin_user_path(user),
                        method: :delete,
                        class: "alert-danger",
                        data: { confirm: "Are you sure?" } %> </td>
            </tr>
          <% end %>

      </table>
    </div>
  </div>
</div>

app/views/admin/users/new.html.erb
<%= render :partial => 'user_form' %>

app/views/admin/users/show.html.erb
<%= render partial: 'shared/admin_nav' %>

<div class = "col-sm-9">
  <h1>User <%= "#{@user.id}: #{@user.full_name}" %></h1>
  <div class = "row">
    <h2>Demographic Information</h2>
    <p> First Name: <%= @user.first_name %></p>
    <p> Last Name: <%= @user.last_name %></p>
    <p> Email: <%= @user.email %></p>

    <p> Default Billing Address:
      <%= display_address("billing", @user) %>
    </p>

    <p> Default Shipping Address:
      <%= display_address("shipping", @user) %>
    </p>

    <%= link_to "Edit #{@user.full_name}'s Information", edit_admin_user_path(@user.id) %>
    <%= link_to "Delete #{@user.full_name}", admin_user_path(@user.id), method: :delete, data: {confirm: "Do you really want to delete this user?"} %>
    <%= link_to "View Saved Addressses",
          addresses_path(:user_id => @user.id) %>
    <%= link_to "View Unplaced Order (Cart)", '#'%>
  </div>


  <div class = "row">
    <h3>Credit Card Infomration</h3>
    <p> First Name: <%= @user.first_name %></p>
    <p> Last Name: <%= @user.last_name %></p>

    <% @user.credit_cards.each do |cc| %>
      <p> Number: <%= cc.card_number %></p>
      <p> Expiration: <%= "#{cc.exp_year}-#{cc.exp_month}" %></p>
      <%= link_to "Remove Card", admin_user_credit_card_path(@user.id, cc.id) , method: :delete%><br>
    <% end %>

  </div>


  <div class = "row">
    <div class = "col-sm-12">
      <h4>Admin Actions for <%= @user.full_name %></h4>
      <div class= "row">
        <%= link_to '#' do %>
          <%= button_tag(type: 'button', class: 'btn btn-lg btn-primary') do
                content_tag(:strong, 'Create Order')
          end %>
        <% end %>
      </div>
      <br>
      <div class= "row">
        <%= link_to 'Create Address', admin_new_address_path(:user_id => @user.id), type: 'button', class: 'btn btn-lg btn-primary' %>
      </div>
    </div>
  </div>
  <br>
  <div class="col-sm-12">
  <%= render partial: "shared/user_order_history", :locals => {:user => @user} %>
  </div>

</div>